name: Atualizar estatísticas GitHub

on:
  schedule:
    - cron: "0 6 * * *"  # Diariamente às 6h UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script Python
        run: python generate_stats.py

      - name: Commit e push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Atualiza estatísticas diariamente [automático]" || echo "Sem mudanças"
          git push
